== BUC_GS - Geld storten
De klant wilt geld storten op een rekening.
Er moet nagegaan worden hoeveel geld ze wilt storten en op welke rekening.

=== Actors

KLANT, medewerker

=== Preconditie

KLANT is geïdentificeerd

=== Basis pad

. De KLANT wilt geld storten op een rekening
. De medewerker vraagt op welke bankrekening
. De KLANT geeft het rekeningnummer waarop het bedrag moet gestort worden.
. De medewerker controleert of het rekeningnummer bestaande is bij deze bank
volgens link:domeinregels.adoc[*DR_VRO*]
. De medewerker vraagt welk bedrag de klant wilt storten.
. De KLANT zegt het bedrag wat erop moet gestort worden en geeft het geld aan de medewerker.
. De medewerker telt het geld na om te zien of het bedrag klopt met wat de klant zegt
. De medewerker moet gegevens van de transactie noteren en bijhouden.
. De medewerker geeft een bewijs af van storting aan klant.
. De use case eindigt

==== Postconditie

Het geld is gestort op desbetreffende rekening dat de klant heeft opgegeven.
DE klant heeft daarvan een bewijs ontvangen van de medewerker.


=== Alternatief A : Stoppen

. De klant kan op elk moment beslissen om te stoppen.
. De medewerker maakt eventuele wijzigingen ongedaan.
. De use case eindigt

==== Postconditie

Niks gewijzigd


=== Alternatief B : Rekeningnummer klopt niet.
[start=2]
. De medewerker merkt dat het opgegeven rekeningnummer van klant niet klopt en dus niet bestaat.
. De medewerker informeert de klant hierover en vraagt om een correcte rekeningnummer.
. De use case gaat verder in stap 2 van het basispad.


== Scenario's


=== SC-GS-001
KLANT: MICHAEL +
rekeningnummer = BE00000000000001 +
PAD: Basispad

=== SC-GS-002 
KLANT: MICHAEL +
rekeningnummer = BE00000000000001 +
PAD: Basispad en Alternatief A: Stoppen 

MICHAEL kijkt op zijn uurwerk en ziet dat hij geen tijd heeft om de transactie af te handelen en zegt dit aan de medewerker.
Het scenario eindigt.

=== SC-GS-003
KLANT: MICHAEL +
rekeningnummer = foutief rekeningnummer 
PAD: Basispad en Alternatief B: rekeningnummer klopt niet 

Scenario gaat verder in stap 2 van het basispad.

